service: gdax-lambda-buyer

custom:
  stage: ${opt:stage, self:provider.stage}
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 10
  environment:
    GDAX_PASSPHRASE: ${file(./credentials.json):${self:custom.stage}.gdaxPassphrase}
    GDAX_API_KEY: ${file(./credentials.json):${self:custom.stage}.gdaxAPIKey}
    GDAX_API_SECRET: ${file(./credentials.json):${self:custom.stage}.gdaxAPISecret}
    GDAX_URI: ${file(./credentials.json):${self:custom.stage}.gdaxURI}
    FIAT_TYPE: 'USD'
    DAILY_DEPOSIT: 10
    BTC: True
    ETH: True
    LTC: True
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  buyBitcoin:
    handler: handler.buyBitcoin
    events:
      - schedule: rate(1 day)
  buyEthereum:
    handler: handler.buyEthereum
    events:
      - schedule: rate(1 day)
  buyLitecoin:
    handler: handler.buyLitecoin
    events:
      - schedule: rate(1 day)
  deposit:
    handler: handler.deposit
    events:
      - schedule: rate(1 day)

plugins:
  - serverless-webpack
